-- ------------------------------------------------------------
-- 資料表 cases
-- 來源: localhost:3306 / pymedical_innodb
-- 產生: 資料表結構匯出工具 v1.3  2026-08-11 16:01:24
-- ------------------------------------------------------------

-- 本檔不含 DROP 陳述式。目標資料庫若已有同名物件，
-- 匯入會停在錯誤 1050 (Table already exists)。

SET NAMES utf8mb4;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

CREATE TABLE `cases` (
  `CaseKey` int(11) NOT NULL AUTO_INCREMENT,
  `PatientKey` int(11) NOT NULL DEFAULT 0,
  `Name` varchar(100) DEFAULT NULL,
  `CaseDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `StartDate` datetime DEFAULT NULL,
  `DoctorDate` datetime DEFAULT NULL,
  `ChargeDate` datetime DEFAULT NULL,
  `Visit` varchar(4) DEFAULT NULL,
  `RegistTypex` varchar(10) DEFAULT NULL,
  `RegistType` varchar(10) DEFAULT NULL,
  `TourArea` varchar(20) DEFAULT NULL,
  `TreatType` varchar(100) DEFAULT NULL,
  `Injury` varchar(50) DEFAULT NULL,
  `SpecialCode` char(2) DEFAULT NULL,
  `Share` varchar(50) DEFAULT NULL,
  `InsType` varchar(4) DEFAULT NULL,
  `ApplyType` varchar(8) DEFAULT NULL,
  `PharmacyType` varchar(10) DEFAULT NULL,
  `Card` varchar(15) DEFAULT NULL,
  `Continuance` int(11) DEFAULT NULL,
  `XCard` varchar(6) DEFAULT NULL,
  `Period` varchar(4) DEFAULT NULL,
  `ChargePeriod` varchar(4) DEFAULT NULL,
  `Room` int(11) NOT NULL DEFAULT 1,
  `MassageRoom` int(11) DEFAULT NULL,
  `RegistNo` int(11) DEFAULT NULL,
  `MassageNo` int(11) DEFAULT NULL,
  `ChargeNo` int(11) DEFAULT NULL,
  `DrugNo` int(11) DEFAULT NULL,
  `YearlyNo1` int(11) DEFAULT NULL,
  `YearlyNo2` int(11) DEFAULT NULL,
  `YearlyNo3` int(11) DEFAULT NULL,
  `Doctor` varchar(10) DEFAULT NULL,
  `Pharmacist` varchar(10) DEFAULT NULL,
  `Massager` varchar(10) DEFAULT NULL,
  `Register` varchar(10) DEFAULT NULL,
  `Casher` varchar(10) DEFAULT NULL,
  `Cashier` varchar(10) DEFAULT NULL,
  `MassageReferrer` varchar(20) DEFAULT NULL,
  `NursingAssistant` varchar(20) DEFAULT NULL,
  `ReceiptShare` int(11) DEFAULT NULL,
  `SDiagShareFee` int(11) DEFAULT NULL,
  `SDrugShareFee` int(11) DEFAULT NULL,
  `Weight` int(11) DEFAULT NULL,
  `Temperature` int(11) DEFAULT NULL,
  `BPHigh` int(11) DEFAULT NULL,
  `BPLow` int(11) DEFAULT NULL,
  `Symptom` mediumtext DEFAULT NULL,
  `Tongue` longtext DEFAULT NULL,
  `Pulse` longtext DEFAULT NULL,
  `Equipment` varchar(8) DEFAULT NULL,
  `DiseaseCode1` varchar(10) DEFAULT NULL,
  `DiseaseName1` varchar(40) DEFAULT NULL,
  `DiseaseCode2` varchar(10) DEFAULT NULL,
  `DiseaseName2` varchar(40) DEFAULT NULL,
  `DiseaseCode3` varchar(10) DEFAULT NULL,
  `DiseaseName3` varchar(40) DEFAULT NULL,
  `DiseaseCode4` varchar(10) DEFAULT NULL,
  `DiseaseName4` varchar(40) DEFAULT NULL,
  `DiseaseCode5` varchar(10) DEFAULT NULL,
  `DiseaseName5` varchar(40) DEFAULT NULL,
  `Distincts` varchar(40) DEFAULT NULL,
  `Cure` varchar(40) DEFAULT NULL,
  `CurativeEffect` int(11) DEFAULT NULL,
  `Remark` longtext DEFAULT NULL,
  `Package1` int(11) DEFAULT NULL,
  `PresDays1` int(11) DEFAULT NULL,
  `Instruction1` varchar(40) DEFAULT NULL,
  `Package2` int(11) DEFAULT NULL,
  `PresDays2` int(11) DEFAULT NULL,
  `Instruction2` varchar(40) DEFAULT NULL,
  `Package3` int(11) DEFAULT NULL,
  `PresDays3` int(11) DEFAULT NULL,
  `Instruction3` varchar(40) DEFAULT NULL,
  `Acupuncture1` enum('False','True') NOT NULL DEFAULT 'False',
  `Acupuncture2` enum('False','True') NOT NULL DEFAULT 'False',
  `EAcupuncture1` enum('False','True') NOT NULL DEFAULT 'False',
  `EAcupuncture2` enum('False','True') NOT NULL DEFAULT 'False',
  `Massage1` enum('False','True') NOT NULL DEFAULT 'False',
  `Massage2` enum('False','True') NOT NULL DEFAULT 'False',
  `Dislocate1` enum('False','True') NOT NULL DEFAULT 'False',
  `Dislocate2` enum('False','True') NOT NULL DEFAULT 'False',
  `Treatment` varchar(100) DEFAULT NULL,
  `Position1` varchar(10) DEFAULT NULL,
  `Position2` varchar(10) DEFAULT NULL,
  `RegistFee` int(11) DEFAULT NULL,
  `DiagFee` int(11) DEFAULT NULL,
  `InterDrugFee` int(11) DEFAULT NULL,
  `PharmacyFee` int(11) DEFAULT NULL,
  `AcupunctureFee` int(11) DEFAULT NULL,
  `MassageFee` int(11) DEFAULT NULL,
  `DislocateFee` int(11) DEFAULT NULL,
  `ExamFee` int(11) DEFAULT NULL,
  `InsTotalFee` int(11) DEFAULT NULL,
  `TreatShare` int(11) DEFAULT NULL,
  `DiagShareFee` int(11) DEFAULT NULL,
  `DrugShare` int(11) DEFAULT NULL,
  `DrugShareFee` int(11) DEFAULT NULL,
  `AgentFee` int(11) DEFAULT NULL,
  `InsApplyFee` int(11) DEFAULT NULL,
  `DepositFee` int(11) DEFAULT NULL,
  `Refund` int(11) DEFAULT NULL,
  `RefundFee` int(11) DEFAULT NULL,
  `SDiagFee` int(11) DEFAULT NULL,
  `SDrugFee` int(11) DEFAULT NULL,
  `SHerbFee` int(11) DEFAULT NULL,
  `SExpensiveFee` int(11) DEFAULT NULL,
  `SAcupunctureFee` int(11) DEFAULT NULL,
  `SMassageFee` int(11) DEFAULT NULL,
  `SDislocateFee` int(11) DEFAULT NULL,
  `SMaterial` int(11) DEFAULT NULL,
  `SMaterialFee` int(11) DEFAULT NULL,
  `SExamFee` int(11) DEFAULT NULL,
  `SelfTotalFee` int(11) DEFAULT NULL,
  `DiscountFee` int(11) DEFAULT NULL,
  `DiscountRate` int(11) DEFAULT 100,
  `TotalFee` int(11) DEFAULT NULL,
  `ReceiptFee` int(11) DEFAULT NULL,
  `Debt` int(11) DEFAULT NULL,
  `DebtFee` int(11) DEFAULT NULL,
  `RegistPaymentType` varchar(20) DEFAULT '現金',
  `ChargePaymentType` varchar(20) DEFAULT '現金',
  `Status` varchar(4) DEFAULT NULL,
  `DoctorDone` enum('False','True') NOT NULL DEFAULT 'False',
  `MassageDone` enum('False','True') NOT NULL DEFAULT 'False',
  `ChargeDone` enum('False','True') NOT NULL DEFAULT 'False',
  `DrugDone` enum('False','True') NOT NULL DEFAULT 'False',
  `DrugPickupDone` enum('False','True') NOT NULL DEFAULT 'False',
  `DesignatedDoctor` enum('False','True') NOT NULL,
  `DesignatedMassager` enum('False','True') NOT NULL,
  `Reference` enum('False','True') NOT NULL DEFAULT 'False',
  `Note` char(1) DEFAULT NULL,
  `Cert` varchar(20) DEFAULT NULL,
  `Message` varchar(40) DEFAULT NULL,
  `Security` longtext DEFAULT NULL,
  `IsClosed` tinyint(1) NOT NULL DEFAULT 0,
  `InvoiceNo` varchar(20) DEFAULT NULL,
  `TimeStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`CaseKey`),
  KEY `PatientKey` (`PatientKey`,`CaseDate`),
  KEY `idx_select_optimization` (`Period`,`RegistType`,`InsType`,`TreatType`,`Doctor`,`DoctorDone`),
  KEY `idx_thc_position1` (`TreatType`,`Position1`),
  KEY `idx_case_date` (`CaseDate`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
