CREATE TABLE `patient` (
  `PatientKey` int(11) NOT NULL AUTO_INCREMENT,
  `CardNo` varchar(12) DEFAULT NULL,
  `ChartNo` varchar(10) DEFAULT NULL,
  `Name` varchar(100) DEFAULT NULL,
  `Era` char(1) DEFAULT NULL,
  `Birthday` date DEFAULT NULL,
  `ID` varchar(10) DEFAULT NULL,
  `Nationality` varchar(4) DEFAULT NULL,
  `Gender` varchar(4) DEFAULT NULL,
  `Sex` varchar(4) DEFAULT NULL,
  `Telephone` varchar(15) DEFAULT NULL,
  `Officephone` varchar(15) DEFAULT NULL,
  `Cellphone` varchar(15) DEFAULT NULL,
  `Email` varchar(100) DEFAULT NULL,
  `ZipCode` varchar(5) DEFAULT NULL,
  `Address` varchar(50) DEFAULT NULL,
  `Marriage` varchar(10) DEFAULT NULL,
  `Education` varchar(10) DEFAULT NULL,
  `Occupation` varchar(10) DEFAULT NULL,
  `DiscountType` varchar(20) DEFAULT NULL,
  `DiscountReason` varchar(40) DEFAULT NULL,
  `InsType` varchar(10) DEFAULT NULL,
  `PrivateInsurance` varchar(10) DEFAULT NULL,
  `FamilyPatientKey` varchar(10) DEFAULT NULL,
  `Reference` varchar(10) DEFAULT NULL,
  `Trace` char(2) DEFAULT NULL,
  `TraceTime` varchar(4) DEFAULT NULL,
  `TraceType` varchar(10) DEFAULT NULL,
  `InitDate` datetime DEFAULT NULL,
  `LastDate` datetime DEFAULT NULL,
  `Alergy` mediumtext DEFAULT NULL,
  `Allergy` mediumtext DEFAULT NULL,
  `History` mediumtext DEFAULT NULL,
  `Description` mediumtext DEFAULT NULL,
  `Remark` mediumtext DEFAULT NULL,
  `Note` char(1) DEFAULT NULL,
  `TimeStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PatientKey`),
  KEY `Birthday` (`Birthday`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
