CREATE TABLE `person` (
  `PersonKey` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) DEFAULT NULL,
  `Birthday` date DEFAULT NULL,
  `Code` varchar(5) DEFAULT NULL,
  `Title` varchar(20) DEFAULT NULL,
  `Position` varchar(10) DEFAULT NULL,
  `FullTime` varchar(10) DEFAULT NULL,
  `ID` varchar(10) DEFAULT NULL,
  `Gender` varchar(2) DEFAULT NULL,
  `Telephone` varchar(15) DEFAULT NULL,
  `Cellphone` varchar(15) DEFAULT NULL,
  `Address` varchar(50) DEFAULT NULL,
  `Email` varchar(100) DEFAULT NULL,
  `Department` varchar(20) DEFAULT NULL,
  `InputDate` date DEFAULT NULL,
  `Password` varchar(6) DEFAULT NULL,
  `Priority` int(11) DEFAULT NULL,
  `IME` varchar(6) DEFAULT NULL,
  `HISDocPK` varchar(20) DEFAULT NULL,
  `Certificate` varchar(50) DEFAULT NULL,
  `CertCardNo` varchar(50) DEFAULT NULL,
  `InitDate` date DEFAULT NULL,
  `QuitDate` date DEFAULT NULL,
  `Remark` varchar(100) DEFAULT NULL,
  `TimeStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PersonKey`),
  KEY `Code` (`Code`)
) ENGINE=MyISAM DEFAULT CHARSET=big5;
