-- ------------------------------------------------------------
-- 資料表 symptom_kt
-- 來源: localhost:3306 / pymedical_innodb
-- 產生: 資料表結構匯出工具 v1.3  2026-08-11 16:01:39
-- ------------------------------------------------------------

-- 本檔不含 DROP 陳述式。目標資料庫若已有同名物件，
-- 匯入會停在錯誤 1050 (Table already exists)。

SET NAMES utf8mb4;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

CREATE TABLE `symptom_kt` (
  `ALM_TYPE` char(2) DEFAULT NULL,
  `ALM_ID` char(10) DEFAULT NULL,
  `ALM_NAME` char(250) DEFAULT NULL,
  `ALM_NAME2` char(250) DEFAULT NULL,
  `ALM_SPCURE` char(10) DEFAULT NULL,
  `ALM_LICNO` char(12) DEFAULT NULL,
  `ALM_ICD9` char(10) DEFAULT NULL,
  `ALM_QUAN` char(10) DEFAULT NULL,
  `ALM_COST` char(10) DEFAULT NULL,
  `ALM_SELL` char(10) DEFAULT NULL,
  `ALM_UNIT` char(2) DEFAULT NULL,
  `ALM_KIND1` char(250) DEFAULT NULL,
  `ALM_KIND2` char(250) DEFAULT NULL,
  `ALM_KIND3` char(250) DEFAULT NULL,
  `ALM_KIND4` char(250) DEFAULT NULL,
  `ALM_KIND5` char(250) DEFAULT NULL,
  `ALM_PHONE` char(250) DEFAULT NULL,
  `ALM_ROMAN` char(250) DEFAULT NULL,
  `ALM_CJ` char(250) DEFAULT NULL,
  `ALM_LOCATE` char(10) DEFAULT NULL,
  `ALM_SAFF` char(10) DEFAULT NULL,
  `ALM_DEFNUM` char(10) DEFAULT NULL,
  `ALM_SELFPAY` char(1) DEFAULT NULL,
  `ALM_CANNUM` char(1) DEFAULT NULL,
  `ALM_CANUNIT` char(1) DEFAULT NULL,
  `ALM_COSTTYPE` char(12) DEFAULT NULL,
  `ALM_COSTKIND` char(1) DEFAULT NULL,
  `ALM_PRNDETAIL` char(1) DEFAULT NULL,
  `ALM_ID2` char(10) DEFAULT NULL,
  `ALM_REMARK` char(20) DEFAULT NULL,
  UNIQUE KEY `SYS_C001304` (`ALM_TYPE`,`ALM_ID`),
  KEY `ALLMENU1` (`ALM_KIND1`),
  KEY `ALLMENU10` (`ALM_ROMAN`),
  KEY `ALLMENU11` (`ALM_NAME`),
  KEY `ALLMENU2` (`ALM_KIND2`),
  KEY `ALLMENU3` (`ALM_KIND3`),
  KEY `ALLMENU4` (`ALM_KIND4`),
  KEY `ALLMENU5` (`ALM_KIND5`),
  KEY `ALLMENU6` (`ALM_ID2`),
  KEY `ALLMENU7` (`ALM_ID`),
  KEY `ALLMENU8` (`ALM_PHONE`),
  KEY `ALLMENU9` (`ALM_CJ`),
  KEY `ALLMENU12` (`ALM_ICD9`),
  KEY `ALLMENU13` (`ALM_COSTTYPE`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
