CREATE TABLE `wait` (
  `WaitKey` int(11) NOT NULL AUTO_INCREMENT,
  `CaseKey` int(11) NOT NULL DEFAULT 0,
  `CaseDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `PatientKey` int(11) NOT NULL DEFAULT 0,
  `RegistrationNo` varchar(10) DEFAULT NULL,
  `Name` varchar(100) DEFAULT NULL,
  `Era` char(1) DEFAULT NULL,
  `Birthday` date DEFAULT NULL,
  `Sex` varchar(4) DEFAULT NULL,
  `Visit` varchar(4) DEFAULT NULL,
  `RegistTypex` varchar(10) DEFAULT NULL,
  `RegistType` varchar(10) DEFAULT NULL,
  `TreatType` varchar(10) DEFAULT NULL,
  `Share` varchar(8) DEFAULT NULL,
  `InsType` varchar(4) DEFAULT NULL,
  `Card` varchar(4) DEFAULT NULL,
  `Continuance` int(11) DEFAULT NULL,
  `Period` varchar(4) DEFAULT NULL,
  `Room` int(11) NOT NULL DEFAULT 1,
  `MassageRoom` int(11) DEFAULT NULL,
  `RegistNo` int(11) DEFAULT NULL,
  `MassageNo` int(11) DEFAULT NULL,
  `Doctor` varchar(10) DEFAULT NULL,
  `InProgress` varchar(10) DEFAULT NULL,
  `Massager` varchar(10) DEFAULT NULL,
  `DoctorDone` enum('False','True') NOT NULL DEFAULT 'False',
  `MassagerDone` enum('False','True') NOT NULL DEFAULT 'False',
  `ChargeDone` enum('False','True') NOT NULL DEFAULT 'False',
  `DrugDone` enum('False','True') NOT NULL DEFAULT 'False',
  `Remark` varchar(100) DEFAULT NULL,
  `TimeStamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`WaitKey`),
  KEY `CaseKey` (`CaseKey`,`CaseDate`,`PatientKey`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
